<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
  <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
  <div class="store">
    <h1>Our <strong>Vinyls</strong></h1>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

    <?php $i=0; foreach ($_productCollection as $_product): ?>
      <?php
          // Reload the product to show custom image attributes
          $productId = $_product->getId();
          $_product = Mage::getModel('catalog/product')->load($productId);

      ?>

      <?php if ($i++%$_columnCount==0): ?>
      <ul class="product-catalog">
      <?php endif ?>

        <li class="product">
          <img class="product__cover" src="<?php echo $this->helper('catalog/image')->init($_product, 'vinyl_cover')->resize(230); ?>"
            width="230" height="230">
          <img class="product__vinyl" src="<?php echo $this->helper('catalog/image')->init($_product, 'vinyl_disc')->resize(230); ?>"
            width="230" height="230">
          <div class="product__price">
            <span class="product__price-currency"><?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?></span>
            <?php echo number_format($_product->getPrice(), 2); ?>
          </div>

          <div class="product__info">
            <h2 class="product-info__title"><?php echo Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'album_title', $_product->getStoreId()); ?></h2>
            <p class="product-info__artist"><?php echo Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'artist', $_product->getStoreId()); ?></p>
            <p class="product-info__spec"><?php echo Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'vinyl_spec', $_product->getStoreId()); ?></p>
          </div>

          <a class="product__detail-link-area" href="<?php echo $_product->getProductUrl(); ?>"></a>
          <a class="product__detail-link" href="<?php echo $_product->getProductUrl(); ?>">Click to view details</a>

          <button type="button" class="product__cart-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">Add to Cart</button>
        </li>

      <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
      </ul>
      <?php endif ?>

    <?php endforeach ?>

    <!--
    <ul class="product-catalog">
      <li class="product">
        <img class="product__cover" src="images/product-001/ATC_WAAATC_250x250_AlbumCover.png">
        <img class="product__vinyl" src="images/product-001/ATC_WAAATC_250x250_Vinyl_MarbleBlue.png">
        <div class="product__price"><span class="product__price-currency">SGD</span> 35.00</div>
        <div class="product__info">
          <h2 class="product-info__title">We are all Amateur Takes Control</h2>
          <p class="product-info__artist">Amateur Takes Control</p>
          <p class="product-info__spec">12" LP Marble Blue Vinyl</p>
        </div>
        <a class="product__detail-link-area" href="/"></a>
        <a class="product__detail-link" href="/">Click to view details</a>
        <button class="product__cart-button">Add to Cart</button>
      </li>

      <li class="product">
        <img class="product__cover" src="images/product-002/ATC_WAAATC_250x250_AlbumCover.png">
        <img class="product__vinyl" src="images/product-002/ATC_WAAATC_250x250_Vinyl_White.png">
        <div class="product__price"><span class="product__price-currency">SGD</span> 35.00</div>
        <div class="product__info">
          <h2 class="product-info__title">We are all Amateur Takes Control</h2>
          <p class="product-info__artist">Amateur Takes Control</p>
          <p class="product-info__spec">12" LP White Vinyl</p>
        </div>
        <a class="product__detail-link-area" href="/"></a>
        <a class="product__detail-link" href="/">Click to view details</a>
        <button class="product__cart-button">Add to Cart</button>
      </li>

      <li class="product">
        <img class="product__cover" src="images/product-003/Satan_Kingbreaker_230x230_AlbumCover_Black.png">
        <img class="product__vinyl" src="images/product-003/Satan_Kingbreaker_230x230_Vinyl_Black.png">
        <div class="product__price"><span class="product__price-currency">SGD</span> 35.00</div>
        <div class="product__info">
          <h2 class="product-info__title">Kingbreaker</h2>
          <p class="product-info__artist">SATAN!</p>
          <p class="product-info__spec">12" LP 180g Vinyl</p>
        </div>
        <a class="product__detail-link-area" href="/"></a>
        <a class="product__detail-link" href="/">Click to view details</a>
        <button class="product__cart-button">Add to Cart</button>
      </li>
    </ul>
    -->
  </div>
<?php endif; ?>

<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script>
  (function() {

    $('.product')
      .mouseover(function() {
        var self = this;
        setTimeout(function() {
          $(self).addClass('product--active');
        }, 10);
      })
      .mouseout(function() {
        var self = this;
        setTimeout(function() {
          $(self).removeClass('product--active');
        }, 10);
      });

  })();
</script>
