<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
  <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
  <div class="store">
    <!-- <h1>Our <strong>Vinyls</strong></h1> -->

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

    <ul class="product-catalog">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
      <?php
          // Reload the product to show custom image attributes
          $productId = $_product->getId();
          $_product = Mage::getModel('catalog/product')->load($productId);

      ?>

        <?php if ( in_array('36', $_product->getCategoryIds()) ) : ?>

          <li class="product">
            <img class="product__cover" src="<?php echo $this->helper('catalog/image')->init($_product, 'vinyl_cover')->resize(230); ?>"
              width="230" height="230">
            <img class="product__vinyl" src="<?php echo $this->helper('catalog/image')->init($_product, 'vinyl_disc')->resize(230); ?>"
              width="230" height="230">
            <div class="product__price">
              <span class="product__price-currency"><?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?></span>
              <?php echo number_format($_product->getPrice(), 2); ?>
            </div>

            <div class="product__info">
              <h2 class="product-info__title"><?php echo $_product->getAlbumTitle(); ?></h2>
              <p class="product-info__artist"><?php echo $_product->getArtist(); ?></p>
              <p class="product-info__spec"><?php echo $_product->getVinylSpec(); ?></p>
            </div>

            <a class="product__detail-link-area" href="<?php echo $_product->getProductUrl(); ?>"></a>
            <a class="product__detail-link" href="<?php echo $_product->getProductUrl(); ?>">Click to view details</a>

            <button type="button" class="product__cart-button"
              onclick="setLocation('<?php echo $this->getAddToCartUrl($_product); ?>')"
              <?php if (!$_product->isSaleable()) : ?>disabled<?php endif; ?>>
              <?php if ($_product->isSaleable()) : ?>
                Add to Cart
              <?php else : ?>
                Out of Stock
              <?php endif; ?>
            </button>
          </li>

        <?php elseif ( in_array('37', $_product->getCategoryIds()) ) : ?>

          <li class="product product--tshirt">
            <img class="product__cover" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(230); ?>"
              width="230" height="230">
            <div class="product__price">
              <span class="product__price-currency"><?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?></span>
              <?php echo number_format($_product->getPrice(), 2); ?>
            </div>

            <div class="product__info">
              <h2 class="product-info__title"><?php echo $_product->getName(); ?></h2>
              <p class="product-info__spec"><?php echo $_product->getModel(); ?></p>
            </div>

            <a class="product__detail-link-area" href="<?php echo $_product->getProductUrl(); ?>"></a>
            <a class="product__detail-link" href="<?php echo $_product->getProductUrl(); ?>">Click to view details</a>

            <button type="button" class="product__cart-button"
              onclick="setLocation('<?php echo $_product->getProductUrl(); ?>')"
              <?php if (!$_product->isSaleable()) : ?>disabled<?php endif; ?>>
              <?php if ($_product->isSaleable()) : ?>
                Add to Cart
              <?php else : ?>
                Out of Stock
              <?php endif; ?>
            </button>
          </li>

        <?php endif; ?>

    <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>

<script src="/skin/frontend/hailsatanrecords/default/js/jquery-1.11.1.min.js"></script>
<script>
  (function() {

    $('.product')
      .mouseover(function() {
        var self = this;
        setTimeout(function() {
          $(self).addClass('product--active');
        }, 10);
      })
      .mouseout(function() {
        var self = this;
        setTimeout(function() {
          $(self).removeClass('product--active');
        }, 10);
      });

  })();
</script>
