<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<div class="vinyl">
  <?php if (count($_product->getMediaGalleryImages()) > 0) : ?>
    <div class="vinyl__gallery">
      <ul class="js-vinyl-slider">
        <?php foreach ($_product->getMediaGalleryImages() as $_image) : ?>
          <li data-thumb="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->resize(90); ?>">
            <a class="js-vinyl-fancybox" href="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->resize(600); ?>" data-fancybox-group="vinyl-fancybox">
              <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->resize(300); ?>" width="300">
            </a>
          </li>
        <?php endforeach; ?>
      </ul>
      <div class="vinyl__gallery-zoom js-vinyl-zoom"></div>
    </div>
  <?php endif; ?>

  <?php // VINYLS ?>
  <?php if ( in_array('36', $_product->getCategoryIds()) || in_array('38', $_product->getCategoryIds()) ) : ?>

    <div class="vinyl__info">
      <h1 class="vinyl__title">
        <?php if ( in_array('36', $_product->getCategoryIds()) ) { echo $_product->getAlbumTitle(); } else { echo $_product->getName(); } ?>
        <b>- <?php echo $_product->getArtist(); ?></b>
      </h1>
      <p class="vinyl__spec"><?php echo $_product->getVinylSpec(); ?></p>

      <?php if ($_product->getDescription()) : ?>
      <div class="vinyl__description">
        <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>
      </div>
      <?php endif; ?>

      <div class="vinyl__actions">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" class="js-product-addtocart-form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
          <?php echo $this->getBlockHtml('formkey') ?>
          <div class="no-display">
              <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
              <input type="hidden" name="related_product" id="related-products-field" value="" />
          </div>
          <div class="vinyl-cart">
            <div class="vinyl-cart__number js-quantity-text"><?php echo $this->getProductDefaultQty() * 1; ?></div>
            <div class="vinyl-cart__add-reduce">
              <div class="vinyl-cart__add-item js-quantity-add">&#9650;</div>
              <div class="vinyl-cart__reduce-item js-quantity-reduce">&#9660;</div>
            </div>
            <input type="hidden" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1; ?>" class="qty js-quantity-input" />
            <button class="vinyl-cart__add" type="submit"
              <?php if (!$_product->isSaleable()) : ?>disabled<?php endif; ?>>
              <?php if ($_product->isSaleable()) : ?>
                Add to Cart
              <?php else : ?>
                Out of Stock
              <?php endif; ?>
            </button>
          </div>
          <div class="vinyl-price">
            <div class="vinyl-price__amount">
              <span class="vinyl-price__currency"><?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?></span>
              <span class="js-vinyl-price"><?php echo number_format($_product->getPrice(), 2); ?></span>
            </div>
            <div class="vinyl-price__label">Total</div>
            <p class="vinyl-price__shipping-info">Shipping costs are calculated when you Checkout</p>
          </div>
        </form>

        <div class="vinyl-share">
          <p class="vinyl-share__text">Share this product with your friends</p>
          <ul class="vinyl-share__media">
            <li><a href="/">Facebook</a></li>
            <li><a href="/">Twitter</a></li>
            <li><a href="/">Pinterest</a></li>
          </ul>
        </div>
        <div class="vinyl-links">
          <a href="/store.html">back to store</a> | <a href="/checkout/cart/">checkout</a>
        </div>
      </div>
    </div>

  <?php // T-SHIRTS ?>
  <?php elseif ( in_array('37', $_product->getCategoryIds()) ) : ?>

    <div class="vinyl__info">
      <h1 class="vinyl__title vinyl__title--tshirt"><?php echo $_product->getName(); ?></h1>
      <p class="vinyl__spec vinyl__spec--tshirt"><?php echo $_product->getModel(); ?></p>

      <?php if ($_product->getDescription()) : ?>
      <div class="vinyl__description">
        <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>
      </div>
      <?php endif; ?>

      <div class="vinyl__actions">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" class="js-product-addtocart-form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
          <?php echo $this->getBlockHtml('formkey') ?>
          <div class="vinyl__no-display">
              <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
              <input type="hidden" name="related_product" id="related-products-field" value="" />
              <?php
                // use your own attribute code here 
                $attribute_code = "shirt_size";
                $attribute_details = Mage::getSingleton("eav/config")->getAttribute("catalog_product", $attribute_code);
                $attribute_options = $attribute_details->getSource()->getAllOptions(false);
              ?>
              <select class="js-vinyl-size-dropdown" name="super_attribute[<?php echo $attribute_details->getAttributeId(); ?>]">
                <?php foreach ($attribute_options as $_option) : ?>
                  <option value="<?php echo $_option["value"] ?>" <?php if ($_option["value"] == '99') echo 'selected' ?>><?php echo $_option["label"] ?></option>
                <?php endforeach; ?>
              </select>
          </div>
          <div class="vinyl-size">
            <div class="vinyl-size__label">Size</div>
            <ul class="vinyl-size__selector js-vinyl-size-selector">
              <li data-size="100">S</li>
              <li data-size="99" class="vinyl-size__selector--selected">M</li>
              <li data-size="98">L</li>
              <li data-size="125">XL</li>
            </ul>
            <a href="/" class="vinyl-size__chart-link">Size & Fit</a>
          </div>

          <div class="vinyl-cart">
            <div class="vinyl-cart__number js-quantity-text"><?php echo $this->getProductDefaultQty() * 1; ?></div>
            <div class="vinyl-cart__add-reduce">
              <div class="vinyl-cart__add-item js-quantity-add">&#9650;</div>
              <div class="vinyl-cart__reduce-item js-quantity-reduce">&#9660;</div>
            </div>
            <input type="hidden" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1; ?>" class="qty js-quantity-input" />
            <button class="vinyl-cart__add" type="submit"
              <?php if (!$_product->isSaleable()) : ?>disabled<?php endif; ?>>
              <?php if ($_product->isSaleable()) : ?>
                Add to Cart
              <?php else : ?>
                Out of Stock
              <?php endif; ?>
            </button>
          </div>
          <div class="vinyl-price">
            <div class="vinyl-price__amount">
              <span class="vinyl-price__currency"><?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?></span>
              <span class="js-vinyl-price"><?php echo number_format($_product->getPrice(), 2); ?></span>
            </div>
            <div class="vinyl-price__label">Total</div>
            <p class="vinyl-price__shipping-info">Shipping costs are calculated when you Checkout</p>
          </div>
        </form>

        <div class="vinyl-share">
          <p class="vinyl-share__text">Share this product with your friends</p>
          <ul class="vinyl-share__media">
            <li><a href="/">Facebook</a></li>
            <li><a href="/">Twitter</a></li>
            <li><a href="/">Pinterest</a></li>
          </ul>
        </div>
        <div class="vinyl-links">
          <a href="/store.html">back to store</a> | <a href="/checkout/cart/">checkout</a>
        </div>
      </div>
    </div>

  <?php endif; ?>
</div>

<script src="/skin/frontend/hailsatanrecords/default/js/jquery-1.11.1.min.js"></script>
<script src="/skin/frontend/hailsatanrecords/default/js/jquery.lightSlider.min.js"></script>
<script src="/skin/frontend/hailsatanrecords/default/js/jquery.fancybox.pack.js"></script>
<script>
  (function() {

    var $vinylSlider = $('.js-vinyl-slider');

    $vinylSlider.lightSlider({
      slideWidth: 300,
      slideMargin: 0,
      slideMove: 1,
      minSlide: 1,
      maxSlide: 1,
      controls: false,
      loop: false,
      thumbWidth: 90,
      thumbMargin: 15,
      gallery: true,
      useCSS: true,
      mode: 'fade',
      onSliderLoad: function() {
        var $vinylFancybox = $('.js-vinyl-fancybox');

        $vinylFancybox.fancybox({
          loop: false
        });

        $('.js-vinyl-zoom').click(function() {
          var index = $vinylSlider.find('li').index($('.active'));

          $.fancybox.open($vinylFancybox, {
            loop: false,
            index: index
          });
        });
      }
    });

    var $qtyInput = $('.js-quantity-input');
    var basePrice = <?php echo number_format($_product->getPrice(), 2); ?>;

    $('.js-quantity-add').on('click', function() {
      var currentQty = parseInt($qtyInput.val(), 10);

      $qtyInput.val(currentQty + 1).trigger('change');
    });

    $('.js-quantity-reduce').on('click', function() {
      var currentQty = parseInt($qtyInput.val(), 10);

      if (currentQty <= 1) return;

      $qtyInput.val(currentQty - 1).trigger('change');
    });

    $qtyInput.on('change', function() {
      var qty = parseInt($(this).val(), 10);
      var totalPrice = (qty * basePrice).toFixed(2);
      $('.js-quantity-text').text(qty);
      $('.js-vinyl-price').text(totalPrice);
    });

    var $productForm = $('.js-product-addtocart-form');
    $productForm.on('submit', function() {
      if (this.qty.value <= 0) {
        alert("Please add quantity.");
        return false;
      }
    });

    $('.js-vinyl-size-selector').on('click', 'li', function() {
      var $this = $(this);
      var selectedSizeId = $this.data('size');
      // console.log('button value:', $(this).data('size'));

      $this.siblings().removeClass('vinyl-size__selector--selected');
      $this.addClass('vinyl-size__selector--selected');
      $('.js-vinyl-size-dropdown').val(selectedSizeId);

      // console.log('dropdown value:', $('.js-vinyl-size-dropdown')[0].value);
    });

  })();
</script>
