<!DOCTYPE html>
<html>
<head>
  <?php echo $this->getChildHtml('head') ?>
</head>
<body <?php echo $this->getBodyClass() ? 'class="'.$this->getBodyClass().' page-product"' : 'page-home' ?>>
  <?php echo $this->getChildHtml('header') ?>

  <div class="site-content">
    <section class="content">
      <?php echo $this->getChildHtml('content') ?>
    </section>
  </div>

  <?php echo $this->getChildHtml('footer') ?>
</body>
</html>