<?php
  $collection = Mage::getModel('catalog/product')->getCollection();
  $collection->addAttributeToSelect('artist');
  $collection->addFieldToFilter('artist', 'Amateur Takes Control');
?>

<div class="band band--atc">
  <a class="band__back-link" href="/bands/">Back to <b>bands</b></a>
  <br>
  <div class="band__logo">
    <img src="/media/wysiwyg/atc/atc-logo--black.png">
  </div>
  <h1 class="band__title">Amateur Takes Control</h1>
  <div class="band__description">
    <div class="band__description__first-col">
      <p>Originally started as a solo project by guitarist Adel Rashid, Amateur Takes Control (ATC) has evolved to its present core line-up of Adel and Isa Ong, with an additional 3 sessionists complementing it’s live performances.</p>
      <p>Amateur Takes Control creates music which is undeniably diverse in style and influence, yet still manages to showcase a seamlessness that justifies their identity as a group. Inspired by the simplest of things like life, love and waking up in the morning realizing you have another day to be thankful for, ATC strives to translate these inspirations into their brand of heartfelt instrumental music.</p>
      <p>Known for their intense onstage performances and dedication to their craft, these young men have a passion about the music they’re creating, helping them receive invitations to prominent shows such as RockStar Collective’s Block Party in Singapore, ZoukOut 2009 and the Motion Picture Soundtrack series of shows at Laundry Bar, Kuala Lumpur. This, and their prolific releases, has helped ATC garner a sizeable following both in Singapore and Malaysia. Amateur Takes Control has opened for plus/minus (+/-) (US), Envy (JPN), LITE (JPN) and Bitch Magnet (US).</p>
    </div>
    <div class="band__description__second-col">
      <p>The band has two previously self-released EPs “Built on Miles of Hope” and “Amateur Takes Control” released in April 2008 and August 2007 respectively. Their 2008 full length, “You, Me And The Things Unsaid” debuted on KittyWu Records.</p>
      <p>As of 28 July 2013, Amateur Takes Control is on an “indefinite hiatus” but are excited to be releasing their first vinyl record "We Are All Amateur Takes Control" out on Hail Satan Records.</p>
    </div>
  </div>
  <div class="band__photo">
    <img src="/media/wysiwyg/atc/atc-photo.png" width="474">
  </div>
  <div class="band-info">
    <div class="band-info__item">
      <h2 class="band-info__title">Get Music from The Band</h2>
      <ul class="band-albums">
        <?php foreach ($collection as $_product) : ?>
          <?php
            // Reload the product to show custom image attributes
            $productId = $_product->getId();
            $_product = Mage::getModel('catalog/product')->load($productId);
          ?>
          <li class="band-albums__item">
            <a class="band-albums__link" href="<?php echo $_product->getProductUrl(); ?>">
              <img class="band-albums__cover" src="<?php echo $this->helper('catalog/image')->init($_product, 'vinyl_cover')->resize(90); ?>" width="90" height="90">
              <p class="band-albums__title"><?php echo $_product->getAlbumTitle(); ?></p>
              <p class="band-albums__spec"><?php echo $_product->getVinylSpec(); ?></p>
            </a>
          </li>
        <?php endforeach; ?>
      </ul>
    </div>
    <div class="band-info__item">
      <h2 class="band-info__title">Follow The Band</h2>
      <p class="band-social"><a href="/">Facebook</a> | <a href="/">Bandcamp</a></p>
    </div>
  </div>
</div>
