<?php
  $collection = Mage::getModel('catalog/product')->getCollection();
  $collection->addAttributeToSelect('artist');
  $collection->addFieldToFilter('artist', 'SATAN!');
?>

<div class="band band--satan">
  <a class="band__back-link" href="/bands/">Back to <b>bands</b></a>
  <br>
  <div class="band__logo">
    <img src="/media/wysiwyg/satan/satan-logo--black.png">
  </div>
  <h1 class="band__title">SATAN!</h1>
  <div class="band__description">
    <div class="band__description__first-col">
      <p>Brought together to satisfy the intangible need for something more, Satan! is in the pursuit of reiterating and challenging the sounds they have in their heads.</p>
      <p>Their debut release, Kingbreaker, is both the search and the vehicle. It threads on familiar grounds driven and benchmarked by heavyweights like Neurosis and Jesu, but the weighted imprints left by the personnel behind Satan! leave deep impressions in these threaded grounds. One would get the feeling of slowly getting pulled off shore when the needle is dropped on the first track. Slowly floating further in before getting pummeled by lengthy waves of low end frequencies. </p>
    </div>
    <div class="band__description__second-col">
      <p>The constant barrage of riffs and weight seem to narrate a running theme of despair and destruction but what makes this record unique is the lacing of nuances that one might not necessarily associate with abrasive music. </p>
      <p>What the listeners can take from Satan! is the need to rid the restlessness of being too comfortable. To not necessarily take the baton and forge something new altogether, but to always have the thirst to push, to crave for something more.</p>
    </div>
  </div>
  <div class="band__photo">
    <img src="/media/wysiwyg/satan/satan-photo.png" width="474">
  </div>
  <div class="band-info">
    <div class="band-info__item">
      <h2 class="band-info__title">Get Music from The Band</h2>
      <ul class="band-albums">
        <?php foreach ($collection as $_product) : ?>
          <?php
            // Reload the product to show custom image attributes
            $productId = $_product->getId();
            $_product = Mage::getModel('catalog/product')->load($productId);
          ?>
          <li class="band-albums__item">
            <a class="band-albums__link" href="<?php echo $_product->getProductUrl(); ?>">
              <img class="band-albums__cover" src="<?php echo $this->helper('catalog/image')->init($_product, 'vinyl_cover')->resize(90); ?>" width="90" height="90">
              <p class="band-albums__title"><?php echo $_product->getAlbumTitle(); ?></p>
              <p class="band-albums__spec"><?php echo $_product->getVinylSpec(); ?></p>
            </a>
          </li>
        <?php endforeach; ?>
      </ul>
    </div>
    <div class="band-info__item">
      <h2 class="band-info__title">Follow The Band</h2>
      <p class="band-social"><a href="/">Facebook</a> | <a href="/">Bandcamp</a></p>
    </div>
  </div>
</div>
