<ul class="bands-showcase">
  <li class="bands-showcase__item">
    <a class="bands-showcase__link" href="/band-amateur-takes-control/">
      <div class="bands-showcase__name-bg"></div>
      <h2 class="bands-showcase__name">Amateur Takes Control</h2>
      <div class="bands-showcase__logo">
        <img src="/media/wysiwyg/atc/atc-logo--white.png">
      </div>
      <img class="bands-showcase__member-pic" src="/media/wysiwyg/atc/atc-photo--gradient.jpg">
    </a>
  </li>

  <li class="bands-showcase__item">
    <a class="bands-showcase__link" href="/band-satan/">
      <div class="bands-showcase__name-bg"></div>
      <h2 class="bands-showcase__name">Satan!</h2>
      <div class="bands-showcase__logo">
        <img src="/media/wysiwyg/satan/satan-logo--white.png">
      </div>
      <img class="bands-showcase__member-pic" src="/media/wysiwyg/satan/satan-photo--gradient.jpg">
    </a>
  </li>
</ul>