<div class="site-footer">
  <footer>
    <div class="site-footer__section">
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Updates</h6>
      </div>
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Vinyls</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/">Featured Releases</a></li>
          <li class="footer-menu__item"><a href="/">New Vinyls</a></li>
          <li class="footer-menu__item"><a href="/">Top Sellers</a></li>
          <li class="footer-menu__item"><a href="/">Vinyl Records</a></li>
        </ul>
      </div>
    </div>

    <div class="site-footer__section">
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Merchandise</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/">T-shirts</a></li>
          <li class="footer-menu__item"><a href="/">Posters</a></li>
        </ul>
      </div>
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Bands</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/">SATAN!</a></li>
          <li class="footer-menu__item"><a href="/">Amateur Takes Control</a></li>
        </ul>
      </div>
    </div>

    <div class="site-footer__section">
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Account</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/">Your Account</a></li>
          <li class="footer-menu__item"><a href="/">Your Cart</a></li>
          <li class="footer-menu__item"><a href="/">Your Wishlist</a></li>
        </ul>
      </div>
      <div class="footer-menu">
        <h6 class="footer-menu__heading">FAQ</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/">Shipping Info</a></li>
          <li class="footer-menu__item"><a href="/">Terms & Conditions</a></li>
        </ul>
      </div>
    </div>

    <div class="site-footer__section">
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Follow Us</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/">Facebook</a></li>
          <li class="footer-menu__item"><a href="/">Instagram</a></li>
          <li class="footer-menu__item"><a href="/">Twitter</a></li>
        </ul>
      </div>
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Contact Us</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/">info@hailsatanrecords.com</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>