<div class="site-footer">
  <footer>
    <div class="site-footer__section">
      <div class="footer-menu footer-menu--inactive">
        <h6 class="footer-menu__heading">Updates</h6>
      </div>
      <div class="footer-menu footer-menu--inactive">
        <h6 class="footer-menu__heading">Vinyls</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/store.html">Featured Releases</a></li>
          <li class="footer-menu__item"><a href="/">New Vinyls</a></li>
          <li class="footer-menu__item"><a href="/">Top Sellers</a></li>
          <li class="footer-menu__item"><a href="/">Vinyl Records</a></li>
        </ul>
      </div>
    </div>

    <div class="site-footer__section">
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Merchandise</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/store.html">T-shirts</a></li>
          <li class="footer-menu__item"><a href="/store.html">Posters</a></li>
        </ul>
      </div>
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Bands</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/band-satan/">SATAN!</a></li>
          <li class="footer-menu__item"><a href="/band-amateur-takes-control/">Amateur Takes Control</a></li>
        </ul>
      </div>
    </div>

    <div class="site-footer__section">
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Account</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item footer-menu__item--inactive"><a href="/">Your Account</a></li>
          <li class="footer-menu__item"><a href="/checkout/cart/">Your Cart</a></li>
          <li class="footer-menu__item footer-menu__item--inactive"><a href="/">Your Wishlist</a></li>
        </ul>
      </div>
      <div class="footer-menu">
        <h6 class="footer-menu__heading">FAQ</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="/shipping-info/">Shipping Info</a></li>
          <li class="footer-menu__item"><a href="/terms-and-conditions/">Terms & Conditions</a></li>
        </ul>
      </div>
    </div>

    <div class="site-footer__section">
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Follow Us</h6>
        <ul class="footer-menu__list footer-menu__list--social">
          <li class="footer-menu__item footer-menu__item--facebook"><a href="https://www.facebook.com/hailsatanrecords">Facebook</a></li>
          <li class="footer-menu__item footer-menu__item--instagram"><a href="http://instagram.com/hailsatan_records">Instagram</a></li>
          <li class="footer-menu__item footer-menu__item--twitter"><a href="https://twitter.com/hailsatanrecord">Twitter</a></li>
        </ul>
      </div>
      <div class="footer-menu">
        <h6 class="footer-menu__heading">Contact Us</h6>
        <ul class="footer-menu__list">
          <li class="footer-menu__item"><a href="mailto:info@hailsatanrecords.com">info@hailsatanrecords.com</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>