<?php
  $urlString = Mage::helper('core/url')->getCurrentUrl();
  $url = Mage::getSingleton('core/url')->parseUrl($urlString);
  $path = $url->getPath();
?>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title><?php echo $this->getTitle(); ?> | Hail Satan Records</title>
<meta name="description" content="Official website of Hail Satan Records. Find our vinyl records here. MUSIC. ART. BLASPHEMY.">
<meta name="keywords" content="hail satan records, vinyl records, vinyls">

<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/skin/frontend/hailsatanrecords/default/css/lightSlider.css">
<link rel="stylesheet" href="/skin/frontend/hailsatanrecords/default/css/jquery.fancybox.css">
<link rel="stylesheet" href="/skin/frontend/hailsatanrecords/default/css/style.css">

<?php if (strpos($path, 'contacts') != 0 || strpos($path, 'paypal/express/review') != 0) echo $this->getCssJsHtml(); ?>
<?php // echo $this->getChildHtml(); ?>

<script>
  window.setLocation = function(url) {
    window.location.href = url;
  };
</script>
<script src="/js/mage/cookies.js"></script>

<?php Mage::getSingleton('checkout/session')->setContinueShoppingUrl('/store.html'); ?>

<?php // Prefetch background images for carousel ?>
<link rel="prefetch" href="/skin/frontend/hailsatanrecords/default/css/img/carousel-1.jpg">
<link rel="prefetch" href="/skin/frontend/hailsatanrecords/default/css/img/carousel-2.jpg">
<link rel="prefetch" href="/skin/frontend/hailsatanrecords/default/css/img/carousel-3.jpg">
