<div class="site-header">
  <header>
    <div class="site-logo"><a href="/">Homepage</a></div>
    <nav class="site-nav site-nav--first">
      <ul>
        <li class="site-nav__item site-nav__item--current"><a href="/">Home</a></li>
        <li class="site-nav__separator"></li>
        <li class="site-nav__item"><a href="/updates">Updates</a></li>
        <li class="site-nav__separator"></li>
        <li class="site-nav__item"><a href="/store.html">Store</a></li>
      </ul>
    </nav>
    <nav class="site-nav site-nav--last">
      <ul>
        <li class="site-nav__item"><a href="/bands">Bands</a></li>
        <li class="site-nav__separator"></li>
        <li class="site-nav__item"><a href="/about">About</a></li>
        <li class="site-nav__separator"></li>
        <li class="site-nav__item"><a href="/contacts">Contact</a></li>
      </ul>
    </nav>
    <nav class="site-nav site-nav--actions">
      <ul>
        <li class="site-nav__item"><a href="/customer/account/login">Log In/Register</a></li>
        <li class="site-nav__separator"></li>
        <li class="site-nav__item"><a href="/checkout/cart">Cart (0)</a></li>
        <li class="site-nav__separator"></li>
        <li class="site-nav__item"><a href="/shipping-info">Shipping Info</a></li>
      </ul>
    </nav>
  </header>
</div>